package dev.marc.japanesehelper.core.text

/** English texts of the grammar points, keyed by rule id (French texts live in Grammar.kt). */
internal class GrammarText(val title: String, val explanation: String, val example: String, val pattern: String? = null)

internal val GRAMMAR_EN: Map<String, GrammarText> = mapOf(
    // ---------------- Particles ----------------
    "wa" to GrammarText("Topic", "Marks the topic of the sentence: what we are talking about (\"as for…\"). Pronounced \"wa\". Can also mark a contrast.", "As for me, I'm a student."),
    "ga-subject" to GrammarText("Subject", "Marks the grammatical subject, often new or emphasized information.", "The rain falls."),
    "ga-but" to GrammarText("But", "Links two contrasting clauses (\"…, but…\"), rather formal.", "It's expensive, but tasty."),
    "wo" to GrammarText("Direct object", "Marks what the action applies to. Also the place one goes through or leaves.", "To read a book."),
    "ni" to GrammarText("Destination, place, time, recipient", "Point of arrival: where one goes or where something is, a specific time, the person one gives or speaks to, a purpose; the agent of a passive verb.", "To go to the station."),
    "he" to GrammarText("Direction", "Direction of movement (\"towards\"). Pronounced \"e\".", "To head east."),
    "de" to GrammarText("Place of action, means, cause", "Where the action takes place, the means or tool used, a cause, or a scope (\"at\", \"by\", \"with\").", "To go by train."),
    "to" to GrammarText("With, and", "Links nouns exhaustively (\"and\") or marks who one does something with.", "To talk with a friend."),
    "to-quote" to GrammarText("Quotation", "Marks what is said, thought or named (\"that…\").", "He said he would go."),
    "to-cond" to GrammarText("Natural consequence", "After a verb: natural or habitual consequence (\"when…, then…\").", "When spring comes, it gets warmer."),
    "mo" to GrammarText("Also, even", "\"Also\"; with a negative \"not… either\"; after a number, stresses the amount.", "I'm going too."),
    "no" to GrammarText("Link between two nouns", "Links two nouns: possession or specification (\"'s\", \"of\"). The first noun qualifies the second.", "My book."),
    "no-nominal" to GrammarText("Nominalization", "Turns a clause into a noun (\"the act of…\", \"the one who…\").", "I like reading."),
    "noda" to GrammarText("Explanation, emphasis", "Presents the sentence as an explanation or background (\"it's that…\").", "It's that I'm tired."),
    "kara-from" to GrammarText("From", "Starting point in space or time, or origin (\"from\", \"since\").", "I came from Tokyo."),
    "kara-because" to GrammarText("Because", "After a clause: the reason (\"because\", \"so\"), rather subjective tone.", "It's cold, so I'm going home."),
    "made" to GrammarText("Until, up to", "Limit in space or time (\"until\", \"as far as\").", "To work until 5."),
    "yori" to GrammarText("Comparison", "\"Than\" in a comparison (A より B: B rather than A); in writing, also \"from\".", "It's hotter than yesterday."),
    "ya" to GrammarText("And (non-exhaustive list)", "Lists examples without being exhaustive (\"… and …, among others\").", "Books, magazines and such."),
    "ka" to GrammarText("Question", "At the end of a sentence: question. Between two nouns: \"or\". After a question word: \"some…\".", "Are you going?"),
    "kana" to GrammarText("I wonder if…", "Doubt or a question to oneself, casual tone (\"I wonder if…\").", "I wonder if he'll understand."),
    "ne" to GrammarText("Isn't it?", "At the end of a sentence: seeks agreement or rapport (\"right?\", \"isn't it?\").", "Nice weather, isn't it."),
    "yo" to GrammarText("Assertion", "At the end of a sentence: gives new information or insists (\"you know\", \"I tell you\").", "It's good, you know."),
    "na-prohibition" to GrammarText("Prohibition", "After a plain present verb, at the end of a sentence: blunt negative command (\"don't…!\").", "Don't move!"),
    "shika" to GrammarText("Only (with a negative)", "しか + negative verb = \"nothing but\", \"only\": stresses how little.", "I only have 100 yen."),
    "dake" to GrammarText("Only", "Limit (\"only\", \"just\"), without a negative judgment.", "Just one."),
    "bakari" to GrammarText("Nothing but, only ever", "\"Nothing but\", \"do nothing but\"; after た: \"have just done\".", "He does nothing but play."),
    "hodo" to GrammarText("To the extent of, about", "Degree (\"to the point of\") or approximate amount; A ほど〜ない: \"not as … as A\".", "Tired to death."),
    "kurai" to GrammarText("About, to the extent of", "Approximate amount (\"about\") or degree (\"to the point of\").", "About ten minutes."),
    "nado" to GrammarText("Etc., for example", "Gives examples (\"among others\", \"such as\").", "Apples, among others."),
    "kedo" to GrammarText("But (casual)", "\"But\", \"though\"; at the end of a sentence, softens or leaves it hanging.", "I'd like to go, but I have no time."),
    "noni" to GrammarText("Even though, despite", "Contrast with a nuance of surprise, reproach or regret (\"even though…\").", "He didn't come even though he promised."),
    "node" to GrammarText("Because (explanation)", "Reason presented objectively and politely (\"since\", \"as\").", "Since it's raining, I won't go."),
    "nagara" to GrammarText("While…", "Two simultaneous actions by the same subject (\"while…\"); sometimes \"although\".", "To talk while walking."),
    "tari" to GrammarText("Doing things like…", "Lists actions as examples (\"doing things like… and…\").", "Reading, writing, things like that."),
    "shi" to GrammarText("And what's more", "Piles up reasons or facts (\"and…\", \"besides…\").", "It's cheap, and what's more it's good."),
    "demo" to GrammarText("Even, … or something", "After a noun: \"even\"; offers an example among others (\"a coffee or something\").", "Even a child understands."),
    "sae" to GrammarText("Even", "\"Even\" (extreme case); さえ〜ば: \"if only…\".", "I don't even know his name."),
    "koso" to GrammarText("Precisely, this very…", "Strongly emphasizes the preceding word.", "This year for sure."),
    "tte" to GrammarText("Casual quotation", "Spoken equivalent of と / という: \"they say\", \"(what's called)…\".", "He says he's coming tomorrow."),
    "toka" to GrammarText("Things like", "Gives vague examples, casual tone.", "I watch movies and stuff."),

    // ---------------- Verb forms and auxiliaries ----------------
    "ta" to GrammarText("Past, completed action", "Past form of verbs, adjectives and the copula; also a completed action.", "I ate."),
    "nai" to GrammarText("Negation", "Negative form (\"not\"). Conjugates like an i-adjective.", "I don't understand."),
    "nu" to GrammarText("Negation (literary or casual)", "Old negation: ぬ (written, archaic), ん (spoken), ず / ずに (\"without…\").", "Without knowing."),
    "masu" to GrammarText("Polite form", "Makes the verb polite (neutral-polite style, with strangers).", "I'm going."),
    "desu" to GrammarText("Polite copula", "\"To be\" in polite style; also makes an adjective polite.", "I'm a student."),
    "da" to GrammarText("Copula", "\"To be\" in plain style (だ, だった, で…).", "I'm a student."),
    "dearu" to GrammarText("Written copula", "\"To be\" in written style (narration, explanations, articles): である, であった.", "It was the Fujiwara clan."),
    "na-adjective" to GrammarText("Na-adjective before a noun", "な links a na-adjective (or みたい, よう) to the noun it describes.", "A quiet room.", "〜な + noun"),
    "teiru" to GrammarText("Ongoing action, state", "Action in progress, a habit, or a state resulting from a past action. Often shortened to 〜てる in speech.", "Was equipped with (state)."),
    "teshimau" to GrammarText("Completed action (regret)", "Action completely finished, often unintended or regretted (\"end up\", \"unfortunately\").", "I ate it all (oops)."),
    "teoku" to GrammarText("Do in advance", "Do something in preparation, or leave something in a state.", "Buy it in advance."),
    "temiru" to GrammarText("Try", "Do something to see (\"try doing\").", "Taste it and see."),
    "tekuru" to GrammarText("Change, direction", "てくる: towards the speaker or the present (\"start to\"). ていく: away, or continuing into the future.", "It's starting to get cold."),
    "tearu" to GrammarText("Resulting state (intended)", "Something has been done (by someone) and the state remains.", "The window has been opened (and is open)."),
    "tekureru" to GrammarText("Doing a favor", "Doing something for someone: くれる (for me), もらう (I receive the favor), あげる (I do it for someone).", "He explained it to me."),
    "temoii" to GrammarText("Permission", "\"You may\", \"it's fine if…\".", "May I read it?"),
    "tewaikenai" to GrammarText("Prohibition", "\"You must not\", \"not allowed to\". Spoken: 〜ちゃいけない / 〜じゃだめ.", "No smoking here."),
    "rareru" to GrammarText("Passive, potential or respect", "Depending on context: passive (\"be …ed by\"), potential (\"can\"), or respectful form.", "Was seen."),
    "saseru" to GrammarText("Causative", "\"Make\" or \"let\" someone do something.", "To make someone study."),
    "saserareru" to GrammarText("Causative-passive", "\"Be made to\" (someone makes me do it).", "I was made to study."),
    "tai" to GrammarText("Desire", "\"Want to\" (for oneself); conjugates like an i-adjective.", "I want to go."),
    "volitional" to GrammarText("Volitional", "Suggestion (\"let's\") or intention (\"I will\").", "Let's go!"),
    "youtoomou" to GrammarText("Intend to", "Volitional + と思う: \"I'm thinking of doing\", \"I intend to\".", "I'm thinking of going."),
    "ba" to GrammarText("Condition", "\"If\": the condition brings about the consequence.", "If it's cheap, I'll buy it."),
    "nakereba" to GrammarText("Obligation", "\"Must\", \"have to\" (literally \"if one doesn't, it won't do\"). Spoken: 〜なきゃ.", "I have to go."),
    "tara" to GrammarText("If, when", "Condition or time (\"if…\", \"once…\", \"when…\").", "I'll call when I arrive."),
    "nara" to GrammarText("If it's…", "Condition on a topic that has come up (\"if that's the case…\", \"as for…\").", "Japanese, I can speak."),
    "sou-looks" to GrammarText("Appearance", "After a verb or adjective stem: \"looks like\", \"seems about to…\".", "It looks like it's going to rain."),
    "sou-hearsay" to GrammarText("Hearsay", "After a full form: \"I heard that\", \"apparently\".", "Apparently it'll rain tomorrow."),
    "you" to GrammarText("Resemblance, manner", "\"Like\", \"seems\" (ようだ, ような); \"so that\" (ように).", "A situation like that of an independent country."),
    "mitai" to GrammarText("Like, seems (casual)", "Casual equivalent of ようだ.", "Someone like a cat."),
    "rashii" to GrammarText("Apparently, typical of", "Guess based on evidence (\"apparently\"); after a noun: \"typical of\", \"worthy of\".", "Apparently he isn't coming."),
    "koto-dekiru" to GrammarText("Can (ability)", "\"Be able to\", \"have the possibility to\".", "I can swim."),
    "takotogaaru" to GrammarText("Experience", "\"Have done before\" (at least once).", "I've been there before."),
    "koto" to GrammarText("Nominalization", "こと turns a clause into a noun (\"the act of…\").", "I like reading."),
    "tsumori" to GrammarText("Intention", "\"Intend to\", \"plan to\".", "I plan to go."),
    "hazu" to GrammarText("Should (expectation)", "What should logically be true (\"normally…\", \"is supposed to\").", "He should have arrived by now."),
    "beki" to GrammarText("Should (moral duty)", "What one ought to do (\"should\").", "You should apologize."),
    "o-prefix" to GrammarText("Politeness prefix", "お / ご before a noun: politeness or respect.", "Tea."),
)
